version: "3.3"
services:
  slurmbase:
    image: slurmbase
    build:
      context: .
      dockerfile: slurmbase
  slurmctl:
    hostname: slurmctl
    image: slurmctl
    build:
      context: .
      dockerfile: slurmctl
    depends_on:
      - slurmbase
  node1:
    hostname: node1
    image: node1
    build:
      context: .
      dockerfile: node
    depends_on:
      - slurmbase
